export const BOARDS_UPDATE = "BOARDS_UPDATE"
export const USER_DETAILS_UPDATE = "USER_DETAILS_UPDATE"

/* Actions for mangaging <CalendarViewer>*/
export const CALENDAR_UNIT_UPDATE = "CALENDAR_UNIT_UPDATE" 
export const CALENDAR_MONTH_UPDATE = "CALENDAR_MONTH_UPDATE" 
export const CALENDAR_YEAR_UPDATE = "CALENDAR_YEAR_UPDATE" 

/* Actions for selecting dates and date ranges */
export const DATE_RANGE_TYPE_UPDATE = "DATE_RANGE_TYPE_UPDATE"
export const DATE_RANGE_START_UPDATE = "DATE_RANGE_START_UPDATE"
export const DATE_RANGE_END_UPDATE = "DATE_RANGE_END_UPDATE"
export const POST_TARGET_DATE_UPDATE = "POST_TARGET_DATE_UPDATE"

/* Actions for managing current content */
export const CURRENT_BOARD_UPDATE = "CURRENT_BOARD_UPDATE"
export const CURRENT_BOARD_POSTS_UPDATE = "CURRENT_BOARD_POSTS_UPDATE"
export const CURRENT_POST_UPDATE = "CURRENT_POST_UPDATE"