export const HAS_INIT_UPDATE = "HAS_INIT_UPDATE"
export const BOARDS_UPDATE = "BOARDS_UPDATE"
export const USER_DETAILS_UPDATE = "USER_DETAILS_UPDATE"

/* Actions for managing current content */
export const CURRENT_BOARD_UPDATE = "CURRENT_BOARD_UPDATE"
export const CURRENT_BOARD_POSTS_UPDATE = "CURRENT_BOARD_POSTS_UPDATE"
export const CURRENT_POST_UPDATE = "CURRENT_POST_UPDATE"